opam-version: "2.0"
maintainer: "Robur <team@robur.coop>"
authors: ["Robur <team@robur.coop>"]
homepage: "https://github.com/robur-coop/contruno"
dev-repo: "git+https://github.com/robur-coop/contruno.git"
bug-reports: "https://github.com/robur-coop/contruno/issues"
license: "MIT"

depends: [
  "ocaml" {>= "5.0.0"}
  "dune" {>= "3.0.0" & build}
  "mirage-crypto-rng-mkernel"
  "mkernel"
  "mnet-cli"
  "mnet-dns"
  "art"
  "mhttp-client"
  "emile"
  "mnet-happy-eyeballs"
  "vifu"
  "ca-certs-nss"
  "mirage-ptime"
  "cattery"
  "mfat"
  "jws"
  "brr"
  "js_of_ocaml"
  "letsencrypt" {>= "2.1.0"}
  "unic" {build}
  "mfetch" {build}
  "flux"
]
build: [
  [make "all"]
]
synopsis: "A TLS termination proxy as a unikernel"
pin-depends: [
  [ "zarith.dev" "git+https://github.com/mirage/Zarith.git#df8969d9bb95cffca13e31a615189ab27ada0684" ]
]
x-mkernel-pre-build: [
  ["mfetch" "fetch" "--with-dune-file" "--file=_mfetch"]
  ["mfetch" "lock" "--file=_mfetch" "--output=_mfetch.locked"]
]
